ZPI-35-create-sign-in-and-sign-up-page
Maciag312/ZPI-UI pull request #2
Opened 2021-08-19 20:16 UTC by Maciag312

- add authorization api client
- add allow page

2021-08-19 21:01 UTC, bachm44 requested changes

2021-08-19 21:01 UTC, bachm44 commented on src/App.tsx
> +              <Route exact path="/auth">
Move route paths to one file called routes.ts

2021-08-19 21:01 UTC, bachm44 commented on src/App.tsx
>      <div className="App">
Use `<Box>` or `<div>` but not both

2021-08-19 21:10 UTC, bachm44 requested changes

2021-08-19 21:10 UTC, bachm44 commented on src/user/authorization/SignInPage.tsx
> +                                    {show ? "Hide" : "Show"}
Consider using internationalization library (ex. i18n) to keep all strings in one place

2021-08-19 21:10 UTC, bachm44 commented on src/user/authorization/SignUpPage.tsx
> +                            <FormLabel textAlign="left" mb="8px"> Username or email</FormLabel>
There is a space at the front of text. Consider i18n
```suggestion
                            <FormLabel textAlign="left" mb="8px">Username or email</FormLabel>
```

2021-08-19 21:10 UTC, bachm44 commented on src/user/authorization/SignUpPage.tsx
> +                        <Button  onClick={handleSubmit} colorScheme="green" marginTop="20px" size="sm">Sign up</Button>
Prettier or other formatting would be nice

```suggestion
                        <Button onClick={handleSubmit} colorScheme="green" marginTop="20px" size="sm">Sign up</Button>
```

2021-08-19 21:12 UTC, bachm44 requested changes

2021-08-19 21:12 UTC, bachm44 commented on .gitignore
> +yarn.lock
This should not be in .gitignore

2021-08-20 15:17 UTC, Maciag312 commented on src/user/authorization/SignUpPage.tsx
> +        authorizationClientInstance.signUp(creds).then(
toast cannot be inside class, where logic functions belongs, let's discuss it

2021-08-20 15:20 UTC, Maciag312 commented on src/user/authorization/api/AuthorizationClient.tsx
> +    signIn(creds: Creds): Promise<AxiosResponse<any>>
Contract between client and server is not set up yet

2021-08-22 10:45 UTC, merged